export interface IClipboardImg {
    imgPath: string
    /**
     * if the path is generated by the extension -> false
     * if the path is a real file path in system -> true
     */
    shouldKeepAfterUploading: boolean
}
