name: "新功能建议"
description: 给vscode-cnb提一个新功能建议

body:
  - type: dropdown
    id: affected-ui-area
    attributes:
      label: ui上的哪部分与此新功能有关?
      options:
        - 侧边栏控制台
        - 侧边栏控制台随笔列表
        - 侧边栏控制台分类列表
        - 侧边栏控制台工作空间
        - 侧边栏控制台账户信息
        - 侧边栏控制台博客园导航
        - 侧边栏控制台随笔列表右键上下文菜单
        - 侧边栏控制台分类列表右键上下文菜单
        - 设置面板
        - markdown编辑器右键上下文菜单
        - markdown编辑器工具栏
        - 侧边栏文件浏览右键上下文菜单
        - 其他
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: 新功能描述
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "[选填]建议的解决方案"
    validations:
      required: false
